#!/usr/bin/env python3
"""
=============================================================================
STOP — READ THIS BEFORE RUNNING
=============================================================================

This script initialises the CURRENT DIRECTORY as a disposable test repo
for Kanban Orchestra. Run it from an EMPTY directory you created for this.

  mkdir /tmp/my-test-repo && cd /tmp/my-test-repo
  "$ORCHESTRA_DIR/bin/ko-init-test-repo"
  "$ORCHESTRA_DIR/bin/ko-orchestrator"

By default, the created repo has TWO ready items in the kanban DB:
the original off-by-one bugfix task plus a disposable supertask that should
create and then clean up four text files.

Use `--most-simple` to seed only two trivial file-write tasks and skip
the disposable supertask.

WILL REFUSE to run if the directory is non-empty or already a git repo
with existing commits — it does not want to clobber real work.

=============================================================================
"""

import argparse
import os
import subprocess
import sys
from pathlib import Path


def parse_args():
    parser = argparse.ArgumentParser(
        description="Initialize the current directory as a disposable Kanban Orchestra test repo."
    )
    parser.add_argument(
        "--most-simple",
        "--most_simple",
        dest="most_simple",
        action="store_true",
        help="Seed two trivial file-write tasks and skip the disposable supertask.",
    )
    return parser.parse_args()


args = parse_args()

# ---------------------------------------------------------------------------
# Check ORCHESTRA_DIR up front
# ---------------------------------------------------------------------------

_orchestra_env = os.environ.get("ORCHESTRA_DIR", "")
if not _orchestra_env:
    print("ERROR: ORCHESTRA_DIR is not set.", file=sys.stderr)
    sys.exit(1)
orchestra_dir = Path(_orchestra_env).expanduser().resolve()

# ---------------------------------------------------------------------------
# Target directory — always cwd
# ---------------------------------------------------------------------------

target = Path.cwd().resolve()

existing = list(target.iterdir()) if target.exists() else []
if existing:
    print(
        f"ERROR: {target} is not empty. Run this from a fresh empty directory.",
        file=sys.stderr,
    )
    sys.exit(1)

print(f"Initialising test repo in {target}")

# ---------------------------------------------------------------------------
# README
# ---------------------------------------------------------------------------

(target / "README.md").write_text(
    """\
# Kanban Orchestra — Example Test Repo

This is a disposable example repository for testing the Kanban Orchestra pipeline.
It was generated by `init_test_repo.py` and is not meant for real work.

## What's here

- `src/counter.py` — a tiny Python module with a deliberate off-by-one bug
- `src/test_counter.py` — a pytest test that fails until the bug is fixed
- `kanban-orchestra.db` — a pre-seeded kanban DB with ready tasks to run

## Running the pipeline

From this directory:

```bash
"$ORCHESTRA_DIR/bin/ko-orchestrator"
```

The orchestrator will pick up the ready work. By default this includes the
original bugfix task and, unless `--most-simple` was used, the disposable
supertask. With `--most-simple`, it instead runs two trivial file-write tasks.
It will run them through the normal sequence and land
commits in this repo.
""",
    encoding="utf-8",
)
print("Wrote README.md")

(target / ".gitignore").write_text(
    "**/__pycache__/**\n"
    "kanban-orchestra.db\n"
    "kanban-orchestra.db-journal\n"
    "kanban-orchestra.db-shm\n"
    "kanban-orchestra.db-wal\n"
    "kanban-orchestra.lock\n"
    ".kanban-orchestra/\n"
    ".claude/\n"
    ".gemini/\n"
    ".codex/\n",
    encoding="utf-8",
)
print("Wrote .gitignore")

# ---------------------------------------------------------------------------
# Tiny codebase: one file with a deliberate off-by-one bug
# ---------------------------------------------------------------------------

src_dir = target / "src"
src_dir.mkdir()

(src_dir / "counter.py").write_text(
    '''\
def count_up_to(n):
    """Return a list of integers from 1 to n (inclusive)."""
    result = []
    for i in range(1, n):   # BUG: should be range(1, n + 1)
        result.append(i)
    return result


if __name__ == "__main__":
    print(count_up_to(5))
''',
    encoding="utf-8",
)

(src_dir / "test_counter.py").write_text(
    '''\
from counter import count_up_to


def test_count_up_to_includes_n():
    assert count_up_to(5) == [1, 2, 3, 4, 5]


def test_count_up_to_one():
    assert count_up_to(1) == [1]
''',
    encoding="utf-8",
)

print("Wrote src/counter.py  (with deliberate off-by-one bug)")
print("Wrote src/test_counter.py")

# ---------------------------------------------------------------------------
# Git repo initialisation
# ---------------------------------------------------------------------------

def run(*args, cwd=target):
    subprocess.run(list(args), cwd=cwd, check=True)

run("git", "init", "-b", "master")
run("git", "config", "user.email", "test@orchestra.local")
run("git", "config", "user.name", "Orchestra Test")
run("git", "add", ".")
run("git", "commit", "-m", "Initial commit: counter module with off-by-one bug")
print("Initialised git repo with one commit")

# ---------------------------------------------------------------------------
# AI skills (claude / gemini / codex → shared skills in orchestra checkout)
# ---------------------------------------------------------------------------

_scripts_dir = Path(__file__).parent
_shared_scripts_dir = _scripts_dir.parent.parent / "shared_scripts"
sys.path.insert(0, str(_shared_scripts_dir))
try:
    from sync_ai_skill_wrappers import sync_skill_wrappers

    sync_skill_wrappers(target=target, orchestra_dir=orchestra_dir)
finally:
    sys.path.pop(0)

# ---------------------------------------------------------------------------
# Kanban DB
# ---------------------------------------------------------------------------

db_path_raw = os.environ.get("KANBAN_DB")
db_path = Path(db_path_raw).expanduser().resolve() if db_path_raw else target / "kanban-orchestra.db"
db_path.parent.mkdir(parents=True, exist_ok=True)

_db_module_dir = Path(__file__).parent
sys.path.insert(0, str(_db_module_dir))
try:
    import db
finally:
    sys.path.pop(0)

conn = db.connect(str(db_path))

if args.most_simple:
    db.add_task(
        conn,
        "Write helloworld.txt",
        description=(
            "Create `helloworld.txt` at the repo root containing exactly "
            "`Hello, world!` followed by a trailing newline. Make no other "
            "changes. Record that no build step was needed because this is a "
            "purely additive file creation."
        ),
        branch="master",
        coder_agent="haiku",
        status="ready",
        skips=["commit-plan"],
    )
    db.add_task(
        conn,
        "Write second-hello.txt",
        description=(
            "Create `second-hello.txt` at the repo root containing exactly "
            "`Hello again!` followed by a trailing newline. Make no other "
            "changes. Record that no build step was needed because this is a "
            "purely additive file creation."
        ),
        branch="master",
        coder_agent="haiku",
        status="ready",
        skips=["commit-plan", "commit-review"],
    )
else:
    db.add_task(
        conn,
        "Fix off-by-one bug in count_up_to()",
        description=(
            "src/counter.py: range(1, n) should be range(1, n + 1) so that n itself "
            "is included in the output. The test in src/test_counter.py already covers "
            "this and will fail until the fix is applied. Run `python3 -m pytest -q src/` "
            "to verify."
        ),
        branch="master",
        coder_agent="haiku",
        status="ready",
        skips=["commit-plan"],
    )

    db.add_task(
        conn,
        "Kanban Orchestra Framework Test",
        description=(
            "This supertask is a test of the Kanban Orchestra framework. During the "
            "commit-make-supertask phase, create 5 child tasks in sequence: one task "
            "each to create `1.txt`, `2.txt`, `3.txt`, and `4.txt`, followed by a "
            "final cleanup task that deletes all four files."
        ),
        branch="master",
        kind="supertask",
        coder_agent="haiku",
        status="ready",
    )

conn.execute(
    "INSERT OR REPLACE INTO orchestrator_runtime (singleton, status) VALUES (1, 'idle')"
)

conn.commit()
conn.close()
print(
    f"Seeded kanban DB at {db_path}  "
    + (
        "(task 1: write helloworld.txt, task 2: write second-hello.txt and skip review)"
        if args.most_simple
        else "(task 1: fix off-by-one, task 2: ready supertask to create 1.txt-4.txt, then clean them up)"
    )
)

# ---------------------------------------------------------------------------
# Done
# ---------------------------------------------------------------------------

print()
print("Test repo ready.")
print(f"  Repo root : {target}")
print(f"  Kanban DB : {db_path}")
print()
print("Next:")
print('  "$ORCHESTRA_DIR/bin/ko-orchestrator"')
